version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    platform: linux/amd64
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      #- traefik_network
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    platform: linux/amd64
    restart: always
    ports:
      - "9090:80"
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      #- traefik_network
      - network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`sf-manager.duckdns.org`) && PathPrefix(`/phpmyadmin`)"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=duckdns"
     # - "traefik.http.services.phpmyadmin.loadbalancer.server.port=9090"

  backend:
    build: ./backend
    container_name: backend_container
    platform: linux/amd64
    restart: always
    command: >
      sh -c "
        if [ \"$NODE_ENV\" = 'production' ]; then
          echo 'Modo produção: instalando dependências e compilando...' &&
          npm ci &&
          npm run build &&
          echo 'Build concluído. Iniciando servidor...' &&
          exec node dist/main.js;
        else
          npm install &&
          npm run dev;
        fi
      "
    volumes:
      - ./backend:/srv/app
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      #- traefik_network
      - network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`seu.dominio`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=resolver"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

  vue-web:
    container_name: frontend_container
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: >
      sh -c "
        if [ \"$NODE_ENV\" = 'production' ]; then
          echo 'Modo produção: instalando dependências e compilando...' &&
          npm install &&
          npm run build &&
          echo 'Build concluído. Iniciando servidor...' &&
          npx serve -s dist -l 5173;
        else
          npm install &&
          npm run dev;
        fi
      "
    volumes:
      - ./frontend:/srv/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    init: true
    stop_grace_period: 1s
    # networks:
    #   - network
    networks:
      #- traefik_network
      - network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`seu.dominio`)"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=resolver"

volumes:
  mysql_data:

networks:
  #traefik_network:
  #  external: true
  network:
    driver: bridge
